apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgDCGwQtylDE7DzaCriMUkdEWpEgz/7CU/omtpWReUS2rVKqdEta1wMF2s3dDZzMOGx+IPVUs35ToxGX6dLHE9iscEZshUH56AGXIH5FZYU18Pb5IsqCgsEZsSf/h9DOY0TrCbLIeygdknU/lnt2ScuxffzI9I+BB2HIx3eImYdoQFYS6pAvP3jQO5W8unGJYFQMExWJVYup5onjDgC3bKjyk1zBTxkW/6So6ClfQLWDWqeZzM4nIJIsnyhWFkuctnS4D/aZLqFFRVDLpu7m4C6rQCtQtLcIC9lVROCbs8Je76Wx0x17V5yBzVOlWVak6wODJswvDNgPbZoV0AwRNtw+gwnCMFsU7VlnZ7CwEoe37wZPBDe+xgXY5hNrdPB7WD8nq1udUuAo+9rVSx4Kp/F4Spg2aRJgOQSGEN5pZQkd8AKRg/CQR0EuCIvkHWm9pPQgNXzuPN7hkvqZoZmi0llTeFaolaBgzEBaqnkRDVVe6lNdj2AENLfE0xaqoLIShcq/WNFbU7uPd5rdDKgfe5JbcPAQ7s+z+nHlqZQxqLRNMrmioK5yX9z+ZfW+3y31nCFh/x/ePjh8x+fUfd6HqzV7Wr23pGaor79aVZPDRoAli5MNsmvJi56bErkcXI4pHC/jm2FVcZhZUfL80BumGRAPOcWMP11Q1b2Vgiu37dl10wH16Fy7dnN0jRA1aoig6Ox3FHjWiFiU9LTn3s0kC84R5M1HtTF3tJ9UKAwHWfOlqpmpY0rNmXHlliSkPTEk1nLFh9zZzfPsBYF3XBFx+u/jCF2vLFutlHYqGDUig32NQZ4dgVi5o2Ax48wKScUs/DvGvh4otUf0MHPgO/rvSrQzV7qkLQ/52Faj9rhPKRom7rXTyl3ujNAK8ukloZjplgh1jlpXsGp+Ks+HO76ud/rZ4PTHazV4YSj/CpPi06M=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

