apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgDjTYr5wYpGtvTYyB3HGpsLQXR/eCCPhio09ft69Wk464pTk1xUlC/VJSXNEj4/c+ictQ7k/dst+asVFnd9j7mABoXtzHsyIw90qa7Yy9JDlT0Wq+TAjHzExE/nqTVkdQxga/1yMpgpivRvr9zVvoss4N7i4jxzbc8q7H/itgyjQt8eOwCk2SJ59MUT9RZB9ou+tCLHYrWZSpdghZdGO5kmhh0+Lg0BkZ+77t9jgFeRlLN5fKJqa9NBlK9FPpKQLG1Crlz9zaLKs0dAkkdjd6J0ByMGYXJNVqzMF7X3fH9euHVO4Ran/bd8a6N4Z6JLI3UgNd3OqkXEAd9cZFoJIqGdPws3MmU3ULfNOV0rHzjZLTvB7DY8r9Lg500dDf+PGVAAldQ+2iFNXuMn4tKYtbqinNdzZs+xWfVnjM+zV6NcEThFIdUFjjOQf/b/b9xJvNqZum/j0MEJYllXCqELRYaOkDr/ADx+6HsdgAMkK4v1VhH3hg5UFhnolEw/BzR+AgGWqVVM6eG6xZgSohRprwQpsxGc7J3KsU3U+Jv8tori+11LMD2F3kLOLh0C7UC8ZFnuE3ugpyREdtiJeL210ll2Lp5dhomDbJfymedhp/22MvwiUHmhTIXOkDJ37yU9tJuAEyNBnPFVUMhAECklN+IqLspGdgfOzbekVAk7609NcW/9bfXKoO2fl9cy94r6LvE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

